py/tuber/tuber.py
src/server.cpp
tests/test.py

Underlying C++ or Python code on the server may now issue Python-style warnings:
warnings.warn("foo")
...and have them propagate across the network to the client's Python environment.

Add remote propagation support for warnings in the underlying C++/Python runtime.

---

.github/workflows/cmake.yml
CMakeLists.txt
src/server.cpp
tests/test_module.cpp

This PR introduces a few compatibility fixes, found while attempting to compile the library on an OSX 12.7.3 system with Apple Clang 14.0.0, linking against libhttpserver 0.19.0.
* Update github workflow to latest libhttpserver version
* Fix linking against Boost and libhttpserver libraries
* Fix return value for `render()` and `render_GET()` methods of the `file_resource` class (libhttpserver 0.19.0 dropped the const modifier)
* Fix parsing of returned content (libhttpserver 0.19.0 uses `std::string_view` here)
* Use a C++11-style for-loop in test suite to avoid errors on systems without the C++20 STL.

Various compatibility fixes

---

.github/workflows/cmake.yml
CMakeLists.txt
src/server.cpp
tests/test_module.cpp

This removes the sole dependency on Boost, making it easier to install on lightweight systems.

Use getopt instead of Boost program options

---

src/server.cpp

This avoids a `PyGILState_Check()` failure when `inc_ref()` is called on the imported registry object.

Release the GIL after initializing tuber_resource

---

py/preamble.py
tests/test.py

* Allow sending an empty request to discover what items are contained in the server registry
* Don't export user-defined double-underscore methods of registry objects
* Return errors for invalid requests

Registry discovery improvements

---

py/preamble.py
py/tuber/codecs.py
py/tuber/tuber.py
requirements.txt
src/server.cpp
tests/test.py

The standard HTTP `Accept` header mechanism is used to negotiate the transport format between the client and server.
JSON is assumed to always be an option, while CBOR is used only if available. The `cbor2` module is used for CBOR support, since it seems to be actively maintained and has an interface nicely matching that of the built-in JSON module. 
A major benefit of allowing CBOR is to efficiently handle binary data, but uniform operation with JSON is important as well. To that end, a simple representation is added for the python `bytes` type when encoding to JSON, replacing it with a dictionary containing a key `"bytes"` which maps to a list of integers containing the byte values. This is chosen to match the [encoding used by …

Implement CBOR as an optional alternative transport format

---

.github/workflows/black.yml
py/preamble.py
py/tuber/codecs.py
py/tuber/tuber.py
setup.py
tests/conftest.py
tests/test.py

Adds linting via "black" to CI/CD flow.
Because lint doesn't act on diffs, unfortunately, we also need a bulk reformatting of Python code in order to make this useful.

Adds linter to CI/CD flow

---

.gitignore
pyproject.toml
setup.py

Instead of using separate install flows for the server (tuberd) and client (tuber) code, use Python's setup machinery for both.
In practice, this means teaching Python to compile cmake packages. There is a pybind11 example package I've bent into shape for this.

Teach setuptools to compile tuberd

---

py/tuber/__init__.py
py/tuber/client.py
src/server.cpp

In a resource-constrained server environment, some Python packages (aiohttp) may not be present. These modules are used in client-side tuber code and don't need to work anyway.
This PR breaks the dependence on client-side API code when running in a server-side environment.

tuberd: allow "import tuber" to fail in client-side code

---

py/tuber/client.py
tests/test.py

This requires that `resolve()` or `TuberObject.tuber_resolve()` be called at the start of a script, rather than lazy-loading methods and properties on access.

Create attributes for all remote methods and properties on resolve

---

src/server.cpp
tuber/client.py
tuber/codecs.py
tuber/server.py

Handle all import logic and encoder/decode function construction in the `tuber.codecs` namespace, rather than distributed between the server and client namespaces.
Create a `Codecs` dictionary for keeping track of encoder/decoder functions on the server.

Consolidate codecs for both client and server in one place

---

tests/test.py
tuber/__init__.py
tuber/client.py

Implement a SimpleTuberClient class, with a corresponding SimpleContext.  The API is similar to that of the asynchronous TuberClient, but all methods are called serially.  The context object still enables pooling multiple method calls into a single HTTP request as usual.
The asynchronous client object is now a subclass of the simple class, with the asynchronous methods (e.g. tuber_resolve) overloaded appropriately.

Simple tuber client

---

src/server.cpp
tests/test.py
tuber/client.py

Optionally return a result with an error attribute, instead of raising an error, to ensure that all commands in a batch are executed.

Optionally allow errors in a sequence of remote commands

---

.git_archival.txt
.gitattributes
.github/workflows/cmake.yml
.github/workflows/package.yml
.gitignore
CMakeLists.txt
README.rst
pyproject.toml
setup.py
tests/conftest.py
tests/pytest.ini
tests/test.py
wheels/FindLibHttpServer.cmake
wheels/install_deps.sh

The new package workflow builds pip wheels on linux and mac Github runners any time changes are pushed to the master branch or a pull request.  Dependencies are compiled as static libraries to avoid rpath issues on installation of the tuberd binary.  Tests are integrated into each wheel and run for each operating system and python version. Github version releases trigger uploading the source distribution and all wheels to PyPI.
Notable changes include:
* Simplify versioning to only keep the version tag
* Ensure correct version number is included in sdist tarball
* Consistent discovery and linking of required libraries via both cmake and pip
* Integrate test suite into package wheel
* Manually build all dependencies as static libraries on all runners
NB: The tuberd binary must be linked …

Github actions workflow for creating, testing and uploading package wheels

---

CMakeLists.txt
README.rst
wheels/install_deps.sh

This makes it easier to install the library from source with pip using a single command:
CMAKE_ARGS="-DBUILD_DEPS=yes" pip install tuberd

CMake option to build dependencies locally

---

tests/test.py
tuber/client.py
tuber/server.py

This allows client-side inspection of argument names, types and default values.

Construct valid signatures for remote methods

---

CMakeLists.txt
pyproject.toml
src/server.cpp
tests/conftest.py
tests/test.py
tuber/server.py

This avoids having wrestle with codecs and python objects in the C++ code, and significantly reduces the overhead for replacing the server with some other implementation in the future.

Migrate request handling to python

---

tuber/client.py

This explicitly avoids a deprecation warning in Python 3.10+, where Futures cannot be created outside of a running event loop.

Create asyncio Future within running event loop

---

requirements.txt
tests/test.py
tuber/client.py

This PR rearranges the `SimpleContext` object to use a `FuturesSession` for dispatching HTTP requests to a thread pool, rather than waiting for them to complete on the main thread.  This brings the API for the `SimpleContext` object in line with that of the async `Context` object.  `TuberObject` methods are executed serially without `await`, and context methods return a `Future` whose `result()` method returns the corresponding result from the server.  Calling a context directly blocks until it responds, akin to the `await ctx()` API of the async `Context`.
To allow for asynchronous communication with several servers, the (non-blocking) `SimpleContext.send()` method returns a `Future` object whose (blocking) `result()` method contains the full `requests.Response` object as processed from …

Bring serial API in line with async using requests-futures

---

requirements.txt
tests/conftest.py
tests/test.py
tuber/schema.py

This adds jsonschema tests to all test cases, without bringing these checks into the normal server or client code at runtime. It works by creating a MITM proxy server that inspects all JSON and CBOR traffic on the way past, validating against either a request or response schema.
The schema check needs a little more work:
* Requests/response inspection is only skin deep - it does not check, for example, metadata descriptions
* Error returns when schema checks fail are piped through the proxy's HTTP response to the server - which is fairly cheeseball

Schema check crashland

---

tuber/server.py

This PR allows using the main() function in the `__main__` block of user code. For example:
```
registry = {"my_object": MyObject()}
if __name__ == "__main__":
from tuber.server import main
main(registry=registry)
```
The registry script then automatically provides the `tuberd` command-line interface, with the registry pre-loaded by the user.
This PR also replaces the fragile `exec` call with an importlib interface for loading a registry from a file path.

Expose tuber.server.main() for user API

---

.github/workflows/cmake.yml
CMakeLists.txt
README.rst
src/server.cpp
wheels/install_deps.sh

`fmt` isn't adding much value, and can be mildly annoying, e.g. by default it builds only a static library but tuber now doesn't like linking with that. It's simpler to just stop using it.

Remove dependency on fmt

---

CMakeLists.txt
tests/test.py
tuber/client.py
tuber/schema.py
tuber/server.py

This PR extends the tuber API to enable dynamic attributes of TuberObjects.
Registry objects on the server may have attributes that are themselves registry objects.  To mark an attribute as such on the server, add the `__tuber_object__` attribute set to `True`.  Registry objects may also add metadata to the description returned from the server by providing a `tuber_meta()` method that returns a dictionary.
One implementation of such a registry object is the `TuberContainer` class -- this implements an interface for lists or dicts of registry objects. Importantly, all of the objects in a container must have the same set of attributes.  To create a container object on the server, wrap your list or dict object in a `TuberContainer` constructor.  Containers may also be attributes of other …

Dynamic object attributes

---

tuber/client.py
tuber/server.py

* Ensure that array elements all have the same type.
* Assign tuber_get method attribute only to container objects.

Some minor fixes for TuberContainer objects

---

src/server.cpp
tuber/server.py

This option currently only affects outputs to stderr from the file service endpoint, and is largely redundant with what the file server would return to the user anyway.  It makes some sense to remove this option so that users don't expect verbose output from the tuber endpoint by enabling it.

Drop --verbose option from server

---

src/server.cpp
tuber/server.py

Only connect the file server endpoint if a user provides a valid filepath. Raise an error if the file path is invalid, and let python handle the error rather than moving on with a printed statement.

Disable file server endpoint by default

---

tuber/client.py

This PR fixes a bug in which the first argument in a method signature was being swallowed when the method wrapper was bound to the client object.

Bug fix in client-side method signatures

---

tests/test.py
tuber/client.py
tuber/schema.py
tuber/server.py

Extract argument names and default values from method signatures on the server, and use this metadata to reconstruct the method signature on the client.
This construction avoids spurious code execution on the client side, and thus builds all signatures with unevaluated string annotations.

Server-side signature metadata

---

tuber/client.py

aiodns is now the DefaultResolver when installed, and for some reason, this whole code path doesn't support mDNS resolution.

Prevent mDNS resolver breakage via aiodns

---

.github/workflows/cmake.yml
tuber/server.py

This warning adds confusion when the cbor codec is not in use.

Don't warn about missing codec on server startup

---

tuber/client.py

If an error is raised by the server while constructing the response message, then the response futures are not populated with either exceptions or results. Calling .result() on such futures may cause the code to hang indefinitely. Prevent this behavior by canceling the futures, so that any attempt to access a result will immediately raise an error.

Cancel all futures on serialization error

---

tuber/client.py
tuber/codecs.py
tuber/server.py

This allows handling return values from the server directly as dicts, which may be more intuitive for certain applications.
Also rearrange arguments so that default values for the response parsing can be set by the parent object or the context.
Add better documentation for all public API functions where these options are used.

Option to return dict instead of TuberResult from JSON decoder

---

tuber/client.py
tuber/codecs.py

* Replace TuberObject implementation with types.SimpleNamespace
* Use JSON metadata inside the TuberObject implementation, not TuberObjects
* Don't return anything on tuber_resolve()
* Deprecate is_container() in favour of tuber_is_container()

Metadata cleanup

---

tests/test.py
tuber/client.py

This fixes a bug in which methods that return dictionaries do not obey the convert_json setting.

Ensure SimpleTuberObject method return value is consistent with convert_json option

---

include/tuber_support.hpp
tests/test_module.cpp

pybind11 [version 3+](https://pybind11.readthedocs.io/en/latest/changelog.html#version-3-0-0-july-10-2025) has merged support for "native_enum", which maps to Python's enum.Enum() and derived classes.
I had hoped to sunset `tuber_support.hpp`, which is only present to expose our `str_enum` helper. Unfortunately, native_enum doesn't do this (it still exposes c++'s "all enums are numeric").
This PR maintains our `str_enum`, avoiding template clashes with native_enum. It's opt-in - you get one or the other by choosing your #includes.

pybind11 3+ support - native_enum collides with str_enum
